"""FHIR R4 de-identification transforms (HIPAA Safe Harbor style).

All transform logic lives in this module so it is easy to extend;
``app/main.py`` is just HTTP glue.

Identifying values are REPLACED with realistic fakes (never blanked) so the
scrubbed record stays usable for downstream training. A per-request
:class:`SurrogateMap` guarantees that the same original value always maps to
the same fake value, which preserves FHIR referential integrity, repeated
names across resources, and coherence between structured fields and free text.

De-identification is one-way for the training path: the surrogate map is not
persisted, and it is only returned to the caller when RETURN_MAP=true.
"""

from __future__ import annotations

import copy
import hashlib
import json
import random
import re
import string
from dataclasses import dataclass
from datetime import date, timedelta

from faker import Faker


@dataclass
class ScrubConfig:
    age_strategy: str = "fixed_30"  # "fixed_30" | "preserve_band"
    scrub_freetext: bool = False


# Resource types whose .name is a HumanName worth scrubbing.
NAMED_RESOURCE_TYPES = {"Patient", "Practitioner", "RelatedPerson"}

# Entities Presidio should replace in free text.
FREETEXT_ENTITIES = ["PERSON", "DATE_TIME", "PHONE_NUMBER", "EMAIL_ADDRESS", "LOCATION"]

# A full ISO date or datetime, e.g. "1984-05-21" or "2024-01-10T09:30:00Z".
# Year-only / year-month values are left untouched (already generalized).
_DATE_RE = re.compile(
    r"^(\d{4}-\d{2}-\d{2})"
    r"(T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:[+-]\d{2}:\d{2}|Z)?)?$"
)


def _seed_for(original: str) -> int:
    """Deterministic 64-bit seed derived from the original value."""
    return int.from_bytes(hashlib.sha256(original.encode("utf-8")).digest()[:8], "big")


def _faker_for(original: str) -> Faker:
    f = Faker("en_US")
    f.seed_instance(_seed_for(original))
    return f


def _shift_date(value: str, offset_days: int) -> str:
    """Shift the date part of an ISO date/datetime, preserving time + zone."""
    m = _DATE_RE.match(value)
    if not m:
        return value
    shifted = date.fromisoformat(m.group(1)) + timedelta(days=offset_days)
    return shifted.isoformat() + (m.group(2) or "")


def _fake_birthdate(original: str, strategy: str) -> str:
    today = date.today()
    if strategy == "preserve_band":
        # Keep the real age but generalize it to the midpoint of a 5-year band.
        try:
            dob = date.fromisoformat(original[:10])
            age = max((today - dob).days // 365, 0)
        except ValueError:
            age = 30
        band_low = (age // 5) * 5
        return (today - timedelta(days=int((band_low + 2.5) * 365.25))).isoformat()
    # "fixed_30" (default): ~30 years old with deterministic +/-3y jitter.
    rnd = random.Random(_seed_for("birthdate:" + original))
    jitter = rnd.randint(-3 * 365, 3 * 365)
    return (today - timedelta(days=int(30 * 365.25) + jitter)).isoformat()


class SurrogateMap:
    """Per-request map of original value -> fake value.

    Fakes are generated by a Faker seeded from a hash of the original, so a
    given input is stable across calls; the map itself makes repeated values
    coherent within one request without any persistence.
    """

    def __init__(self) -> None:
        self.mapping: dict[str, str] = {}

    def _get(self, original: str, generate) -> str:
        if original not in self.mapping:
            self.mapping[original] = generate(_faker_for(original))
        return self.mapping[original]

    def given_name(self, original: str, gender: str | None = None) -> str:
        def gen(f: Faker) -> str:
            if gender == "male":
                return f.first_name_male()
            if gender == "female":
                return f.first_name_female()
            return f.first_name()

        return self._get(original, gen)

    def family_name(self, original: str) -> str:
        return self._get(original, lambda f: f.last_name())

    def phone(self, original: str) -> str:
        return self._get(original, lambda f: f.phone_number())

    def email(self, original: str) -> str:
        return self._get(original, lambda f: f.email())

    def street(self, original: str) -> str:
        return self._get(original, lambda f: f.street_address())

    def city(self, original: str) -> str:
        return self._get(original, lambda f: f.city())

    def date_text(self, original: str) -> str:
        return self._get(original, lambda f: f.date(pattern="%B %d, %Y"))

    def identifier(self, original: str) -> str:
        """Same-format replacement: digit->digit, letter->letter (case kept),
        punctuation preserved — so MRN/SSN/account formats survive."""

        def gen(_f: Faker) -> str:
            rnd = random.Random(_seed_for("identifier:" + original))
            out = []
            for ch in original:
                if ch.isdigit():
                    out.append(str(rnd.randint(0, 9)))
                elif ch.isalpha():
                    pool = string.ascii_uppercase if ch.isupper() else string.ascii_lowercase
                    out.append(rnd.choice(pool))
                else:
                    out.append(ch)
            return "".join(out)

        return self._get(original, gen)


# Presidio engines are heavyweight; build once, lazily, at first use.
_ANALYZER = None
_ANONYMIZER = None


def _get_presidio():
    global _ANALYZER, _ANONYMIZER
    if _ANALYZER is None:
        from presidio_analyzer import AnalyzerEngine
        from presidio_analyzer.nlp_engine import NlpEngineProvider
        from presidio_anonymizer import AnonymizerEngine

        provider = NlpEngineProvider(
            nlp_configuration={
                "nlp_engine_name": "spacy",
                # en_core_web_sm keeps builds fast; swap for _lg for better recall.
                "models": [{"lang_code": "en", "model_name": "en_core_web_sm"}],
            }
        )
        _ANALYZER = AnalyzerEngine(nlp_engine=provider.create_engine())
        _ANONYMIZER = AnonymizerEngine()
    return _ANALYZER, _ANONYMIZER


class Scrubber:
    """One instance per request; owns the surrogate map and date-shift offset."""

    def __init__(self, config: ScrubConfig) -> None:
        self.config = config
        self.smap = SurrogateMap()
        self.offset_days = 0

    def scrub(self, resource: dict) -> tuple[dict, dict[str, str]]:
        out = copy.deepcopy(resource)
        patient = _find_patient(out)
        # ONE consistent offset per patient so the intervals between a
        # patient's events are preserved across every resource in the request.
        patient_key = (patient or {}).get("id") or json.dumps(resource, sort_keys=True)[:512]
        rnd = random.Random(_seed_for("date-shift:" + str(patient_key)))
        self.offset_days = rnd.choice([-1, 1]) * rnd.randint(0, 180)
        self._walk(out, resource_type=None, gender=None)
        return out, dict(self.smap.mapping)

    # ------------------------------------------------------------------ walk

    def _walk(self, node, resource_type: str | None, gender: str | None) -> None:
        if isinstance(node, list):
            for item in node:
                self._walk(item, resource_type, gender)
            return
        if not isinstance(node, dict):
            return

        rt = node.get("resourceType", resource_type)
        if node.get("resourceType") == "Patient":
            gender = node.get("gender")

        for key, value in list(node.items()):
            if key == "resourceType":
                continue
            if key == "name" and rt in NAMED_RESOURCE_TYPES and _looks_like_human_name(value):
                self._scrub_names(value, gender if rt == "Patient" else None)
                self._walk(value, rt, gender)  # still date-shift name.period
            elif key == "address":
                self._scrub_addresses(value)
                self._walk(value, rt, gender)
            elif key == "telecom":
                self._scrub_telecoms(value)
                self._walk(value, rt, gender)
            elif key == "identifier":
                self._scrub_identifiers(value)
                self._walk(value, rt, gender)
            elif key == "birthDate" and isinstance(value, str):
                node[key] = _fake_birthdate(value, self.config.age_strategy)
            elif key == "note" and isinstance(value, list):
                for ann in value:
                    if isinstance(ann, dict) and isinstance(ann.get("text"), str):
                        ann["text"] = self._scrub_text(ann["text"])
                self._walk(value, rt, gender)  # date-shift annotation.time
            elif key in ("valueString", "description", "comment", "div") and isinstance(value, str):
                node[key] = self._scrub_text(value)
            elif isinstance(value, str):
                if _DATE_RE.match(value):
                    node[key] = _shift_date(value, self.offset_days)
            else:
                self._walk(value, rt, gender)

    # -------------------------------------------------------- field handlers

    def _scrub_names(self, value, gender: str | None) -> None:
        for name in _as_list(value):
            if not isinstance(name, dict):
                continue
            if isinstance(name.get("given"), list):
                name["given"] = [
                    self.smap.given_name(g, gender) if isinstance(g, str) else g
                    for g in name["given"]
                ]
            if isinstance(name.get("family"), str):
                name["family"] = self.smap.family_name(name["family"])
            if isinstance(name.get("text"), str):
                name["text"] = self._map_person_text(name["text"])

    def _map_person_text(self, text: str) -> str:
        """Token-wise mapping of a full-name string, reusing surrogates already
        assigned to the structured given/family parts so both stay coherent."""
        tokens = text.split()
        out = []
        for i, tok in enumerate(tokens):
            if tok in self.smap.mapping:
                out.append(self.smap.mapping[tok])
            elif i == len(tokens) - 1:
                out.append(self.smap.family_name(tok))
            else:
                out.append(self.smap.given_name(tok))
        return " ".join(out)

    def _scrub_addresses(self, value) -> None:
        for addr in _as_list(value):
            if not isinstance(addr, dict):
                continue
            if isinstance(addr.get("line"), list):
                addr["line"] = [
                    self.smap.street(line) if isinstance(line, str) else line
                    for line in addr["line"]
                ]
            if isinstance(addr.get("city"), str):
                addr["city"] = self.smap.city(addr["city"])
            # state/district are intentionally preserved (state-level geography
            # is allowed under Safe Harbor).
            if isinstance(addr.get("postalCode"), str):
                # Safe Harbor: keep only the first 3 digits of the ZIP. If the
                # 3-digit zone has population < 20,000 it must be blanked
                # ("000"); we don't bundle census data, so plain truncation.
                addr["postalCode"] = addr["postalCode"][:3]
            if isinstance(addr.get("text"), str):
                parts: list[str] = []
                if isinstance(addr.get("line"), list):
                    parts += [p for p in addr["line"] if isinstance(p, str)]
                parts += [
                    addr[k] for k in ("city", "state", "postalCode")
                    if isinstance(addr.get(k), str)
                ]
                addr["text"] = ", ".join(parts)

    def _scrub_telecoms(self, value) -> None:
        for t in _as_list(value):
            if not isinstance(t, dict) or not isinstance(t.get("value"), str):
                continue
            system = t.get("system")
            if system == "email":
                t["value"] = self.smap.email(t["value"])
            elif system in ("phone", "fax", "sms", "pager"):
                t["value"] = self.smap.phone(t["value"])
            else:
                t["value"] = self.smap.identifier(t["value"])

    def _scrub_identifiers(self, value) -> None:
        for ident in _as_list(value):
            if isinstance(ident, dict) and isinstance(ident.get("value"), str):
                # .system and .type are kept so consumers still know what kind
                # of identifier this is; only the value is replaced.
                ident["value"] = self.smap.identifier(ident["value"])

    # ------------------------------------------------------------- free text

    def _scrub_text(self, text: str) -> str:
        if not self.config.scrub_freetext or not text.strip():
            return text
        from presidio_anonymizer.entities import OperatorConfig

        analyzer, anonymizer = _get_presidio()
        results = analyzer.analyze(text=text, entities=FREETEXT_ENTITIES, language="en")
        operators = {
            "PERSON": OperatorConfig("custom", {"lambda": self._map_person_text}),
            "PHONE_NUMBER": OperatorConfig("custom", {"lambda": self.smap.phone}),
            "EMAIL_ADDRESS": OperatorConfig("custom", {"lambda": self.smap.email}),
            "LOCATION": OperatorConfig("custom", {"lambda": self.smap.city}),
            "DATE_TIME": OperatorConfig("custom", {"lambda": self._surrogate_datetime}),
        }
        return anonymizer.anonymize(text=text, analyzer_results=results, operators=operators).text

    def _surrogate_datetime(self, span: str) -> str:
        # ISO dates get the patient's consistent date-shift; anything else
        # (e.g. "last Tuesday", "Jan 3rd") gets a stable fake date.
        if _DATE_RE.match(span):
            return _shift_date(span, self.offset_days)
        return self.smap.date_text(span)


def _as_list(value) -> list:
    return value if isinstance(value, list) else [value]


def _looks_like_human_name(value) -> bool:
    items = _as_list(value)
    return any(
        isinstance(n, dict) and ("given" in n or "family" in n or "text" in n)
        for n in items
    )


def _find_patient(node):
    if isinstance(node, dict):
        if node.get("resourceType") == "Patient":
            return node
        for v in node.values():
            found = _find_patient(v)
            if found is not None:
                return found
    elif isinstance(node, list):
        for v in node:
            found = _find_patient(v)
            if found is not None:
                return found
    return None


def scrub_resource(resource: dict, config: ScrubConfig | None = None) -> tuple[dict, dict[str, str]]:
    """Scrub a FHIR resource or Bundle; returns (scrubbed_copy, surrogate_map)."""
    return Scrubber(config or ScrubConfig()).scrub(resource)
